# Generated by Django 3.2.9 on 2021-12-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '__first__'),
        ('discounting', '0002_alert_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataid', models.CharField(blank=True, max_length=200, null=True)),
                ('name_score', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name_score', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('province_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('district_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('dob_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('pob', models.CharField(blank=True, max_length=200, null=True)),
                ('pob_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('city_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('country_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_match_score', models.CharField(blank=True, max_length=200, null=True)),
                ('discounting_rationale', models.CharField(blank=True, max_length=200, null=True)),
                ('type_discounting_factor', models.CharField(blank=True, max_length=200, null=True)),
                ('proposed_action', models.CharField(blank=True, max_length=200, null=True)),
                ('match_type', models.CharField(blank=True, max_length=200, null=True)),
                ('risk', models.CharField(blank=True, max_length=200, null=True)),
                ('list', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.individual')),
            ],
        ),
    ]
