# Generated by Django 3.2.9 on 2021-12-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounting', '0003_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='discount',
        ),
    ]
